/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-Apr-2021 1:34:08 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Address_Districts]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Address] DROP CONSTRAINT [FK_Address_Districts]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Address_Province]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Address] DROP CONSTRAINT [FK_Address_Province]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Address_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Address] DROP CONSTRAINT [FK_Address_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Category_Category]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Category] DROP CONSTRAINT [FK_Category_Category]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Table1_Discount]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DiscountLog] DROP CONSTRAINT [FK_Table1_Discount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Table1_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DiscountLog] DROP CONSTRAINT [FK_Table1_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Districts_Province]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [District] DROP CONSTRAINT [FK_Districts_Province]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Order_Discount]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_Discount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Order_OrderStatus]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_OrderStatus]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Order_PaymentMethod]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_PaymentMethod]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Order_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrderDetail_Order]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrderDetail] DROP CONSTRAINT [FK_OrderDetail_Order]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrderDetail_Product]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrderDetail] DROP CONSTRAINT [FK_OrderDetail_Product]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_Brand]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product] DROP CONSTRAINT [FK_Product_Brand]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_Category]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product] DROP CONSTRAINT [FK_Product_Category]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_Image]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product] DROP CONSTRAINT [FK_Product_Image]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ProductDetail_Product]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ProductDetail] DROP CONSTRAINT [FK_ProductDetail_Product]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LogProduct_Product]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ProductLog] DROP CONSTRAINT [FK_LogProduct_Product]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Role]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User] DROP CONSTRAINT [FK_User_Role]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Address]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Address]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Brand]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Brand]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Category]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Category]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Discount]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Discount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DiscountLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DiscountLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[District]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [District]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Image]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Image]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Order]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Order]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[OrderDetail]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [OrderDetail]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[OrderStatus]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [OrderStatus]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PaymentMethod]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PaymentMethod]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Product]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Product]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ProductDetail]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ProductDetail]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ProductLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ProductLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Province]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Province]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Role]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User]
GO

/* Create Tables */

CREATE TABLE [Address]
(
	[Id] varchar(50) NOT NULL,
	[ProvinceId] varchar(50) NULL,
	[DistrictId] varchar(50) NULL,
	[Description] varchar(200) NULL,
	[UserId] varchar(50) NULL
)
GO

CREATE TABLE [Brand]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NULL
)
GO

CREATE TABLE [Category]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NOT NULL,
	[IdParent] varchar(50) NULL
)
GO

CREATE TABLE [Discount]
(
	[Id] varchar(50) NOT NULL,
	[Value] decimal(2,2) NULL,
	[Quantity] int NULL,
	[FromDate] datetime NOT NULL,
	[ToDate] datetime NULL
)
GO

CREATE TABLE [DiscountLog]
(
	[UserId] varchar(50) NOT NULL,
	[DiscountId] varchar(50) NOT NULL
)
GO

CREATE TABLE [District]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NULL,
	[ProvinceId] varchar(50) NULL
)
GO

CREATE TABLE [Image]
(
	[Id] varchar(50) NOT NULL,
	[Path] varchar(max) NULL
)
GO

CREATE TABLE [Order]
(
	[Id] varchar(50) NOT NULL,
	[UserId] varchar(50) NULL,
	[CreateAt] varchar(50) NULL,
	[StatusId] varchar(50) NULL,
	[PaymentMethodId] varchar(50) NULL,
	[DiscountId] varchar(50) NULL
)
GO

CREATE TABLE [OrderDetail]
(
	[OrderId] varchar(50) NOT NULL,
	[ProductId] varchar(50) NOT NULL,
	[Price] decimal(18,2) NULL,
	[Discount] decimal(18,2) NULL
)
GO

CREATE TABLE [OrderStatus]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NULL
)
GO

CREATE TABLE [PaymentMethod]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NULL
)
GO

CREATE TABLE [Product]
(
	[Id] varchar(50) NOT NULL,
	[Name] varchar(50) NULL,
	[Description] nvarchar(max) NULL,
	[Quantity] varchar(50) NULL,
	[Price] decimal(18,2) NULL,
	[CategoryId] varchar(50) NULL,
	[BrandId] varchar(50) NULL,
	[ImageId] varchar(50) NULL,
	[Status] varchar(50) NULL,
	[CreateAt] varchar(50) NULL
)
GO

CREATE TABLE [ProductDetail]
(
	[Id] varchar(50) NOT NULL,
	[ProductId] varchar(50) NULL,
	[Ram] varchar(50) NULL,
	[DisplayCard] varchar(200) NULL,
	[Storage] varchar(200) NULL,
	[Audio] varchar(200) NULL,
	[Monitor] varchar(200) NULL,
	[Keyboard] varchar(200) NULL,
	[Port] varchar(200) NULL,
	[OS] varchar(200) NULL,
	[Battery] varchar(200) NULL,
	[Weight] varchar(200) NULL,
	[Color] varchar(200) NULL,
	[Size] varchar(200) NULL,
	[Security] varchar(200) NULL
)
GO

CREATE TABLE [ProductLog]
(
	[Id] varchar(50) NOT NULL,
	[Name] varchar(50) NULL,
	[ProductId] varchar(50) NULL
)
GO

CREATE TABLE [Province]
(
	[Id] varchar(50) NOT NULL,
	[Name] nvarchar(50) NULL
)
GO

CREATE TABLE [Role]
(
	[Id] varchar(50) NOT NULL,
	[Name] varchar(50) NULL
)
GO

CREATE TABLE [User]
(
	[Id] varchar(50) NOT NULL,
	[Username] varchar(50) NOT NULL,
	[Password] varchar(max) NOT NULL,
	[Avatar] varchar(max) NULL,
	[Gender] varchar(50) NULL,
	[Email] varchar(50) NULL,
	[Status] varchar(50) NULL,
	[FullName] nvarchar(50) NULL,
	[Phone] varchar(50) NULL,
	[RoleId] varchar(50) NULL,
	[LoginAt] datetime NULL,
	[CreateAt] datetime NULL,
	[Point] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Address] 
 ADD CONSTRAINT [PK_Address]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Address_Districts] 
 ON [Address] ([DistrictId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Address_Province] 
 ON [Address] ([ProvinceId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Address_User] 
 ON [Address] ([UserId] ASC)
GO

ALTER TABLE [Brand] 
 ADD CONSTRAINT [PK_Brand]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Category] 
 ADD CONSTRAINT [PK_Category]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Category_Category] 
 ON [Category] ([IdParent] ASC)
GO

ALTER TABLE [Discount] 
 ADD CONSTRAINT [PK_Discount]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [DiscountLog] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([UserId] ASC,[DiscountId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Table1_Discount] 
 ON [DiscountLog] ([DiscountId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Table1_User] 
 ON [DiscountLog] ([UserId] ASC)
GO

ALTER TABLE [District] 
 ADD CONSTRAINT [PK_Districts]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Districts_Province] 
 ON [District] ([ProvinceId] ASC)
GO

ALTER TABLE [Image] 
 ADD CONSTRAINT [PK_Image]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Order] 
 ADD CONSTRAINT [PK_Order]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_Discount] 
 ON [Order] ([DiscountId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_OrderStatus] 
 ON [Order] ([StatusId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_PaymentMethod] 
 ON [Order] ([PaymentMethodId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_User] 
 ON [Order] ([UserId] ASC)
GO

ALTER TABLE [OrderDetail] 
 ADD CONSTRAINT [PK_OrderDetail]
	PRIMARY KEY CLUSTERED ([OrderId] ASC,[ProductId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_OrderDetail_Order] 
 ON [OrderDetail] ([OrderId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_OrderDetail_Product] 
 ON [OrderDetail] ([ProductId] ASC)
GO

ALTER TABLE [OrderStatus] 
 ADD CONSTRAINT [PK_OrderStatus]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [PaymentMethod] 
 ADD CONSTRAINT [PK_PaymentMethod]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Product] 
 ADD CONSTRAINT [PK_Product]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Brand] 
 ON [Product] ([BrandId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Category] 
 ON [Product] ([CategoryId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Image] 
 ON [Product] ([ImageId] ASC)
GO

ALTER TABLE [ProductDetail] 
 ADD CONSTRAINT [PK_ProductDetail]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ProductDetail_Product] 
 ON [ProductDetail] ([ProductId] ASC)
GO

ALTER TABLE [ProductLog] 
 ADD CONSTRAINT [PK_LogProduct]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_LogProduct_Product] 
 ON [ProductLog] ([ProductId] ASC)
GO

ALTER TABLE [Province] 
 ADD CONSTRAINT [PK_Province]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Role] 
 ADD CONSTRAINT [PK_Role]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Role] 
 ON [User] ([RoleId] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Address] ADD CONSTRAINT [FK_Address_Districts]
	FOREIGN KEY ([DistrictId]) REFERENCES [District] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Address] ADD CONSTRAINT [FK_Address_Province]
	FOREIGN KEY ([ProvinceId]) REFERENCES [Province] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Address] ADD CONSTRAINT [FK_Address_User]
	FOREIGN KEY ([UserId]) REFERENCES [User] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Category] ADD CONSTRAINT [FK_Category_Category]
	FOREIGN KEY ([IdParent]) REFERENCES [Category] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DiscountLog] ADD CONSTRAINT [FK_Table1_Discount]
	FOREIGN KEY ([DiscountId]) REFERENCES [Discount] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DiscountLog] ADD CONSTRAINT [FK_Table1_User]
	FOREIGN KEY ([UserId]) REFERENCES [User] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [District] ADD CONSTRAINT [FK_Districts_Province]
	FOREIGN KEY ([ProvinceId]) REFERENCES [Province] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_Discount]
	FOREIGN KEY ([DiscountId]) REFERENCES [Discount] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_OrderStatus]
	FOREIGN KEY ([StatusId]) REFERENCES [OrderStatus] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_PaymentMethod]
	FOREIGN KEY ([PaymentMethodId]) REFERENCES [PaymentMethod] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_User]
	FOREIGN KEY ([UserId]) REFERENCES [User] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrderDetail] ADD CONSTRAINT [FK_OrderDetail_Order]
	FOREIGN KEY ([OrderId]) REFERENCES [Order] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrderDetail] ADD CONSTRAINT [FK_OrderDetail_Product]
	FOREIGN KEY ([ProductId]) REFERENCES [Product] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product] ADD CONSTRAINT [FK_Product_Brand]
	FOREIGN KEY ([BrandId]) REFERENCES [Brand] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product] ADD CONSTRAINT [FK_Product_Category]
	FOREIGN KEY ([CategoryId]) REFERENCES [Category] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product] ADD CONSTRAINT [FK_Product_Image]
	FOREIGN KEY ([ImageId]) REFERENCES [Image] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ProductDetail] ADD CONSTRAINT [FK_ProductDetail_Product]
	FOREIGN KEY ([ProductId]) REFERENCES [Product] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ProductLog] ADD CONSTRAINT [FK_LogProduct_Product]
	FOREIGN KEY ([ProductId]) REFERENCES [Product] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [User] ADD CONSTRAINT [FK_User_Role]
	FOREIGN KEY ([RoleId]) REFERENCES [Role] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
